### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by nullified33** [PepperCode1/ConnectedTexturesMod-Fabric#10]
Error loading metadata for sprite minecraft:missingno.
java.io.FileNotFoundException: minecraft:textures/missingno.png
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
	at net.minecraft.resource.NamespaceResourceManager.getResource(NamespaceResourceManager:67)
	at net.minecraft.resource.ReloadableResourceManagerImpl.getResource(ReloadableResourceManagerImpl:64)
	at team.chisel.ctm.client.util.ResourceUtil.getResource(ResourceUtil.java:29)
	at team.chisel.ctm.client.util.ResourceUtil.getMetadata(ResourceUtil.java:51)
	at team.chisel.ctm.client.util.ResourceUtil.getMetadata(ResourceUtil.java:63)
	at team.chisel.ctm.client.util.ResourceUtil.getMetadataSafe(ResourceUtil.java:90)
	at team.chisel.ctm.client.util.TextureUtil.initializeTextures(TextureUtil.java:23)
	at team.chisel.ctm.client.model.CTMUnbakedModel.bake(CTMUnbakedModel.java:54)
	at net.minecraft.client.render.model.ModelLoader.bake(ModelLoader:486)
	at net.minecraft.client.render.model.ModelLoader.method_4733(ModelLoader:249)
	at net.minecraft.class_1088$$Lambda$9160/437027051.accept(Unknown Source)
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeySet.forEach(Object2ObjectOpenHashMap.java:744)
	at net.minecraft.client.render.model.ModelLoader.upload(ModelLoader:246)
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:67)
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager:19)
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13)
	at net.minecraft.class_4080$$Lambda$8805/497604262.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.class_4014$$Lambda$9132/825867891.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70)
	at net.minecraft.class_4014$$Lambda$8799/593286508.execute(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.class_4014$$Lambda$9132/825867891.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70)
	at net.minecraft.class_4014$$Lambda$8799/593286508.execute(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.class_4014$$Lambda$9132/825867891.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70)
	at net.minecraft.class_4014$$Lambda$8799/593286508.execute(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.class_4014$$Lambda$9132/825867891.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70)
	at net.minecraft.class_4014$$Lambda$8799/593286508.execute(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.class_4014$$Lambda$9132/825867891.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70)
	at net.minecraft.class_4014$$Lambda$8799/593286508.execute(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71)
	at net.minecraft.class_4014$$Lambda$9132/825867891.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70)
	at net.minecraft.class_4014$$Lambda$8799/593286508.execute(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_1060$$Lambda$9144/1636052765.execute(Unknown Source)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem:116)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:103)
	at net.minecraft.client.util.Window.swapBuffers(Window:308)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by PepperCode1** [comment]
`missingno` is usually caused by an error in the texture pack, but just a stacktrace like this is not enough information for me to point out the exact problem. If you can provide a resource pack link and other information, I can provide more help.

**Comment by nullified33** [comment]
This is from logs

**Comment by nullified33** [comment]
it loops

**Comment by nullified33** [comment]
is the solution making a texture pack with the texture

**Comment by PepperCode1** [comment]
Sorry this issue went stale, but you didn't provide enough information for me to be able to help. If you are still having this issue, please join the [Discord server](https://discord.gg/7rnTYXu).
